sensor:
  - platform: rest
    name: EM2024_Gruppe A
    unique_id: EM2024_Gruppe_A
    resource: https://site.web.api.espn.com/apis/v2/sports/soccer/uefa.euro/standings 
    value_template: "{{ now() }}"
    json_attributes_path: "$['children'][0]['standings']"
    json_attributes:
      - entries
      
  - platform: rest
    name: EM2024_Gruppe B
    unique_id: EM2024_Gruppe_B
    resource: https://site.web.api.espn.com/apis/v2/sports/soccer/uefa.euro/standings 
    value_template: "{{ now() }}"
    json_attributes_path: "$['children'][1]['standings']"
    json_attributes:
      - entries
      
  - platform: rest
    name: EM2024_Gruppe C
    unique_id: EM2024_Gruppe_c
    resource: https://site.web.api.espn.com/apis/v2/sports/soccer/uefa.euro/standings 
    value_template: "{{ now() }}"
    json_attributes_path: "$['children'][2]['standings']"
    json_attributes:
      - entries
      
  - platform: rest
    name: EM2024_Gruppe D
    unique_id: EM2024_Gruppe_D
    resource: https://site.web.api.espn.com/apis/v2/sports/soccer/uefa.euro/standings 
    value_template: "{{ now() }}"
    json_attributes_path: "$['children'][3]['standings']"
    json_attributes:
      - entries

  - platform: rest
    name: EM2024_Gruppe E
    unique_id: EM2024_Gruppe_E
    resource: https://site.web.api.espn.com/apis/v2/sports/soccer/uefa.euro/standings 
    value_template: "{{ now() }}"
    json_attributes_path: "$['children'][4]['standings']"
    json_attributes:
      - entries

  - platform: rest
    name: EM2024_Gruppe F
    unique_id: EM2024_Gruppe_F
    resource: https://site.web.api.espn.com/apis/v2/sports/soccer/uefa.euro/standings 
    value_template: "{{ now() }}"
    json_attributes_path: "$['children'][5]['standings']"
    json_attributes:
      - entries